version: "3.8"
services:
  api:
    build:
      context: .
    ports:
    - 80
    environment:
      API_VERSION: "1.0"
      API_VERSION: "dev"
      # API_VERSION: "production"
    volumes: {}
      